Recipe/send message to contact
whispir/whispir-node pull request #4
Opened 2022-09-26 07:46 UTC by mneri-whispir

Added sample code for creating a contact and sending a simple message

2022-10-10 06:33 UTC, richardfontein requested changes

2022-10-10 06:33 UTC, richardfontein commented on examples/lib/contact.lib.js
> +const { ContactsApi } = require('@whispir/ztest-node-api')
Should this package instead be `@whispir/whispir-node`?

2022-10-10 06:33 UTC, richardfontein commented on examples/package.json
> +    "@whispir/ztest-node-api": "^1.0.0",
As above, should this be `@whispir/whispir-node`?

2022-10-10 06:33 UTC, richardfontein commented on examples/package.json
> +  "name": "@whispir-node/recipes",
To keep consistent with the `@whispir` scope, should we instead rename this to `@whispir/node-recipes`?

2022-10-10 06:33 UTC, richardfontein commented on examples/whispir-send-message-to-contact/index.js
> +// }
Got some commented code here, I think it can be removed.

2022-10-11 00:24 UTC, mneri-whispir commented
@richardfontein updated with the needed changes. kindly review again. thank you!

2022-11-22 10:30 UTC, closed without merging